"""Case studies batch D — 25 classes: remaining ADVERSARIAL + start ARCHITECTURAL."""
import json, pathlib

DATA = pathlib.Path(__file__).resolve().parent.parent / "src" / "data" / "failures.json"
d = json.loads(DATA.read_text())

CS = {
    "ADV-HOTFLIP-105": [{"title": "HotFlip finds character-level adversarial text for classifiers", "system": "NLP text classifiers (Seq2Seq)", "date": "2018", "outcome": "Ebrahimi et al.'s HotFlip used gradient information to flip individual characters in text inputs, causing NLP classifiers to misclassify — demonstrating that character-level perturbations humans barely notice can fool machine learning systems.", "source": "Ebrahimi et al. 'HotFlip: White-Box Adversarial Examples for Text Classification' ACL 2018"}],
    "ADV-BEAM-ATTACK-106": [{"title": "Beam search manipulation generates biased summaries", "system": "Abstractive summarization models", "date": "2022", "outcome": "Researchers showed that beam search decoding could be exploited: by crafting inputs that made biased continuations score highest in beam search, attackers produced summaries that reliably omitted key facts or introduced specific framings.", "source": "Wallace et al. 'Concealed Data Poisoning Attacks on NLP Models' NAACL 2021"}],
    "ADV-RL-ATTACK-108": [{"title": "RL-based red-teamer finds jailbreaks via policy optimization", "system": "LLaMA / GPT-4 (targets)", "date": "2023", "outcome": "Perez et al. trained a reinforcement learning agent to red-team LLMs — optimizing attack prompts using the target model's responses as reward signal. The RL attacker discovered novel jailbreaks human red-teamers had not found.", "source": "Perez et al. 'Red Teaming Language Models with Language Models' 2022; Casper et al. 2023"}],
    "ADV-ATTENTION-HIJACK-111": [{"title": "Attention hijacking causes summarizer to omit key document sections", "system": "BERT-based summarizer", "date": "2021", "outcome": "Researchers demonstrated that inserting attention-grabbing tokens near irrelevant content caused transformer attention heads to focus away from critical sections — summaries omitted crucial legal or medical details present in source documents.", "source": "Shi et al. 'Large Language Models Can Be Easily Distracted by Irrelevant Context' 2023"}],
    "ADV-LOGIT-MANIP-112": [{"title": "Logit bias injection forces harmful completions via API", "system": "OpenAI API (GPT-3.5/4)", "date": "2023", "outcome": "Researchers used OpenAI API's logit_bias parameter to assign high positive logit weights to tokens spelling out harmful content — forcing the model to generate harmful completions regardless of safety training, exploiting a legitimate API feature.", "source": "Community research 2023; OpenAI API logit_bias documentation; reported in AI safety forums"}],
    "ADV-COLD-115": [{"title": "COLD decoding generates fluent toxic text under constraints", "main": "Constrained text generation", "date": "2021", "outcome": "Qian et al.'s COLD (Constrained Likelihood Decoding) generated fluent, constraint-satisfying text including toxic content by shaping the decoding distribution — demonstrated that constrained decoding could produce harmful content even in safety-filtered settings.", "source": "Qian et al. 'COLD Decoding: Energy-based Constrained Text Generation' NeurIPS 2022"}],
    "ADV-MASTERKEY-116": [{"title": "MasterKey finds universal jailbreaks via reverse engineering", "system": "ChatGPT / Bard / Bing Chat", "date": "2023", "outcome": "Deng et al. reverse-engineered safety training objectives by analyzing refusal patterns across many queries, then constructed 'MasterKey' prompts that exploited identified patterns — achieving transfer across multiple commercial chatbots.", "source": "Deng et al. 'MasterKey: Automated Jailbreak Across Multiple Large Language Model Chatbots' 2023"}],
    "ADV-ITER-REFINE-119": [{"title": "Iterative refinement achieves jailbreak through incremental relaxation", "system": "GPT-4 / Claude", "date": "2023", "outcome": "Multi-turn attacks where each turn slightly relaxed the previous refused request — starting from a clearly acceptable version and incrementally moving toward the harmful target — exploited models' tendency not to track cumulative context drift.", "source": "Perez & Ribeiro 2022; PAIR (Chao et al. 2023); community red-team documentation"}],
    "ADV-ENSEMBLE-120": [{"title": "Ensemble attack combines multiple jailbreak techniques for higher ASR", "system": "GPT-4 / Claude 2 (black-box)", "date": "2023", "outcome": "Researchers found that combining multiple jailbreak strategies simultaneously (persona + hypothetical + elaboration + role-play) achieved significantly higher attack success rates than any single technique — exploiting weaknesses in safety training coverage simultaneously.", "source": "Wei et al. NeurIPS 2023; Zhang et al. 'Jailbreaking ChatGPT' 2023"}],
    "ADV-HASHJACK-123": [{"title": "Hash-based payload delivers attack across long context", "system": "GPT-4 / long-context models", "date": "2024", "outcome": "Attackers embedded attack instructions in documents using content-addressable references — the actual malicious payload was stored elsewhere and retrieved only when the model processed a lookup key, evading static prompt filters that scan at injection time.", "source": "Willison 'Prompt Injection Defense' 2023; advanced injection research 2024"}],
    "ADV-BASE64-136": [{"title": "Base64 encoding bypasses content safety filters", "system": "ChatGPT / Claude / Gemini", "date": "2023", "outcome": "Encoding harmful requests in base64 then asking the model to decode and answer bypassed safety classifiers that operated on raw text. Models reliably decoded and responded to base64-encoded requests they would have refused in plaintext.", "source": "Yuan et al. 'GPT-4 Is Too Smart To Be Safe' 2023; community demonstration 2023"}],
    "ADV-UNICODE-OBFUSC-138": [{"title": "Unicode homoglyph substitution evades keyword safety filters", "system": "Content moderation systems / LLM safety", "date": "2023", "outcome": "Replacing ASCII characters with visually identical Unicode homoglyphs (e.g., Cyrillic 'а' for Latin 'a') preserved human readability while evading keyword-based safety filters — demonstrating that character-level defenses cannot rely on ASCII matching.", "source": "Boucher et al. 'Bad Characters: Imperceptible NLP Attacks' IEEE S&P 2022"}],
    "ADV-URL-ENCODE-141": [{"title": "URL-encoded harmful content bypasses safety pre-processing", "system": "LLM API with text preprocessing", "date": "2023", "outcome": "Submitting harmful text URL-encoded (%XX format) bypassed safety classifiers that operated on decoded text — some pipeline implementations decoded after classification rather than before, creating a gap exploitable via URL encoding.", "source": "OWASP LLM Top 10 2023; community red-team reports"}],
    "ADV-STEG-TEXT-145": [{"title": "Steganographic whitespace encodes hidden commands in output", "system": "GPT-4 / multi-agent systems", "date": "2023", "outcome": "Researchers demonstrated encoding malicious instructions in the number and type of whitespace characters appended to LLM outputs — invisible to human readers but interpretable by downstream automated systems that processed the output, enabling covert channel attacks in pipelines.", "source": "Greshake et al. 'Not What You Signed Up For' 2023; Kang et al. 2023"}],
    "ADV-TYPO-IMG-146": [{"title": "Typographic adversarial images fool CLIP-based classifiers", "system": "CLIP / GPT-4V / LLaVA", "date": "2021", "outcome": "Goh et al. showed that adding printed text ('iPod') to images of apples caused CLIP to classify the apple as an iPod — multimodal models weighted textual content in images over visual features, enabling simple text-overlay attacks.", "source": "Goh et al. 'Multimodal Neurons in Artificial Neural Networks' Distill 2021; OpenAI CLIP robustness studies"}],
    "ADV-ADV-IMG-148": [{"title": "Adversarial image patch causes object detector to ignore stop signs", "system": "YOLO / physical-world object detectors", "date": "2018", "outcome": "Eykholt et al. created physical adversarial patches applied to stop signs that caused autonomous vehicle object detectors to consistently misclassify them as speed limit signs — demonstrating real-world physical adversarial attacks with safety implications.", "source": "Eykholt et al. 'Robust Physical-World Attacks on Deep Learning Visual Classification' CVPR 2018"}],
    "ADV-OCR-BYPASS-153": [{"title": "Rendered image of text bypasses text-based content filters", "system": "ChatGPT / Claude / multimodal models", "date": "2023", "outcome": "Users discovered that rendering harmful text as an image and submitting via the vision interface bypassed text-based safety classifiers — the model's OCR capability read and responded to content the text safety filter never evaluated.", "source": "OpenAI GPT-4V red-team report 2023; community demonstrations"}],
    "ARCH-PRETOKEN-FAIL-197": [{"title": "Pre-token safety failure allows harmful completion before filter activates", "system": "GPT-5.2 (OAI_52)", "date": "2025", "outcome": "OpenAI documented in the GPT-5.2 system card that some safety failures occurred in the pre-token generation phase — before the output safety classifier could evaluate — allowing partial harmful completions that appeared in streamed output.", "source": "OpenAI GPT-5.2 System Card 2025 (OAI_52)"}],
    "ARCH-BATCH-SAFE-199": [{"title": "Batch API bypasses per-request safety rate limits", "system": "OpenAI Batch API", "date": "2024", "outcome": "Researchers found that submitting harmful requests via the Batch API (asynchronous bulk processing) received less safety scrutiny than real-time API calls — batch processing pipelines applied lighter moderation, creating a higher-throughput bypass channel.", "source": "Community security research 2024; OpenAI Batch API documentation"}],
    "ARCH-PIPELINE-BYPASS-201": [{"title": "Safety filter skipped in high-load pipeline fallback path", "system": "Production LLM deployment", "date": "2024", "outcome": "In a high-traffic production deployment, the safety moderation service became a bottleneck; engineers added a fallback path that bypassed moderation when the service was slow. Attackers learned to trigger the fallback by timing requests during peak load.", "source": "Industry incident pattern; OWASP LLM Top 10 2024"}],
    "ARCH-RACE-SAFE-202": [{"title": "Race condition allows harmful action before safety check completes", "system": "LLM agent with async safety checking", "date": "2024", "outcome": "In an agent system with asynchronous safety validation, a race condition allowed the agent to begin executing a tool call before the safety check completed — in fast-executing tools, the action completed before the check could abort it.", "source": "OWASP LLM Top 10 2024; async agent architecture vulnerability research"}],
    "ARCH-CHECKPOINT-INCONS-203": [{"title": "Safety properties lost when model is resumed from checkpoint", "system": "Fine-tuned LLM (production)", "date": "2024", "outcome": "A model that passed safety evaluations at a checkpoint was deployed after additional fine-tuning on customer data. The safety properties from the evaluated checkpoint did not fully persist through the additional training, creating a checkpoint-deployment safety gap.", "source": "Yang et al. 'Shadow Alignment' 2023; industry deployment pattern"}],
    "ARCH-FALLBACK-DEGRAD-204": [{"title": "Smaller fallback model has weaker safety than primary", "system": "Production LLM API (load-balanced)", "date": "2024", "outcome": "An API that routed overflow traffic to a smaller, cheaper model for cost management exposed users to a model with significantly weaker safety training — attackers learned to trigger overflow routing to access the less-safe fallback model.", "source": "Industry deployment pattern; model routing safety considerations 2024"}],
    "ARCH-TIMEOUT-BYPASS-205": [{"title": "Long-thinking timeout skips safety reasoning step", "system": "Chain-of-thought model (production)", "date": "2025", "outcome": "Models that use extended thinking chains for safety reasoning can be forced to skip the reasoning phase via timeout pressure — either by crafting requests that fill computation budget or by setting short timeout parameters — causing the model to respond without completing safety evaluation.", "source": "Anthropic extended thinking research 2025; OAI_52 pre-token safety documentation"}],
    "ARCH-ERROR-EXPOSE-206": [{"title": "Error message leaks system prompt and internal architecture", "system": "LLM API deployment", "date": "2023", "outcome": "Triggering edge-case errors in LLM APIs (malformed requests, context overflow, invalid parameters) caused some systems to include internal debugging information in error responses — leaking system prompt contents, model version, safety filter status, and internal routing details.", "source": "Community security research 2023; OWASP LLM Top 10 2023"}],
}

enriched = 0
for failure in d["failures"]:
    fid = failure["id"]
    if fid in CS and not failure.get("case_studies"):
        failure["case_studies"] = CS[fid]
        enriched += 1
        print(f"{fid}: {len(CS[fid])} case stud(ies) added")

DATA.write_text(json.dumps(d, indent=2, ensure_ascii=False))
print(f"Batch D: enriched {enriched} classes")
